version: '2'

services:
    consul:
        image: smebberson/alpine-consul
        restart: always
        expose:
            - 8500
    consului:
        image: smebberson/alpine-consul-ui
        ports:
            - 8500:8500
        restart: always
    shield-browser:
        image: securebrowsing/shield-browser:latest
        restart: always
        hostname: browser
        shm_size: 1GB
    shield-proxy:
        image: securebrowsing/squid-proxy:latest
        hostname: proxy
        restart: always
        ports:
            - "3128:3128"
    icap-server:
        image: securebrowsing/shield-icap:latest
        hostname: icap-server
        restart: always
        expose:
            - 8500
    shield-broker:
        image: securebrowsing/shield-broker
        hostname: broker
        restart: always
    elk:
        image: alpin3/elk 
        hostname: elk
        ports:
            - "5601:5601"
            - "5044:5044"